# Advanced Machine Learning 

In [140]:
# Load dataset (iris), split into X_train, y_train, X_test, y_test!
# Write your code here 
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt


dataset = datasets.load_iris()

x = dataset.data
x = np.asarray(x)

y = dataset.target
y = np.asarray(y)

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state = 42)

In [57]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## 1. Voting 

In [102]:
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


# Hint: 
# clf_voting = VotingClassifier( estimators=[('label1', clf_1),
#('label2', clf_2),
#('labelN', clf_N)]) 

# Create the individual models
clf_knn = KNeighborsClassifier(10)
clf_dt = DecisionTreeClassifier()
clf_lr = LogisticRegression()

# Create voting classifier
clf_voting = VotingClassifier(estimators=[
('knn', clf_knn),
('dt', clf_dt),
('lr', clf_lr)])

# Fit it to the training set and predict
clf_voting.fit(x_train, y_train)
y_pred = clf_voting.predict(x_test)

# Get the accuracy score
acc = accuracy_score(y_test, y_pred)
print("Accuracy: {:0.3f}".format(acc))

Accuracy: 0.977


D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [68]:
clf_knn.fit(x_train, y_train)
y_pred_knn = clf_knn.predict(x_test)

acc_knn = accuracy_score(y_test, y_pred)
print('accuracy k-NN: {:0.3f}'.format(acc_knn))

#decision tree
clf_dt.fit(x_train, y_train)
y_pred_dt = clf_dt.predict(x_test)
acc_dt = accuracy_score(y_test, y_pred)
print('accuracy dt: {:0.3f}'.format(acc_dt))

#logistic regression
clf_lr.fit(x_train, y_train)
y_pred_lr = clf_lr.predict(x_test)
acc_lr = accuracy_score(y_test, y_pred)
print('accuracy lr: {:0.3f}'.format(acc_lr))


accuracy k-NN: 1.000
accuracy dt: 1.000
accuracy lr: 1.000


D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [61]:
y_pred_knn

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

## 2. Averaging 

In [4]:
# Template for averaging Classifier 

from sklearn.ensemble import VotingClassifier

clf_voting = VotingClassifier(
estimators=[
('label1', clf_1),
('label2', clf_2),
('labelN', clf_N)],
voting='soft',
weights=[w_1, w_2, w_N]
)

In [ ]:
# Initiate the individual models 

# Write your code here! 

# Create averaging classifier

# Write your code here! 

## 3. Bagging

### KNN

In [88]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier

data2 = datasets.load_breast_cancer()

x = data2.data
x = np.asarray(x)

y = data2.target
y = np.asarray(y)

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state = 42)

bagging = BaggingClassifier(KNeighborsClassifier(),
                           max_samples=0.5, max_features=0.5)

In [94]:
bagging.fit(x_train, y_train)

BaggingClassifier(base_estimator=KNeighborsClassifier(algorithm='auto',
                                                      leaf_size=30,
                                                      metric='minkowski',
                                                      metric_params=None,
                                                      n_jobs=None,
                                                      n_neighbors=5, p=2,
                                                      weights='uniform'),
                  bootstrap=True, bootstrap_features=False, max_features=0.5,
                  max_samples=0.5, n_estimators=10, n_jobs=None,
                  oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [97]:
print(confusion_matrix(y_train, bagging.predict(x_train)))

[[123  26]
 [  3 246]]


In [98]:
print(confusion_matrix(y_test, bagging.predict(x_test)))

[[ 55   8]
 [  2 106]]


In [101]:
print('accuracy bagging-bagging: {:0.3f}'.format(accuracy_score(y_test, bagging.predict(x_test))))

accuracy bagging-bagging: 0.942


### Random Forest

In [103]:
bagging = BaggingClassifier(RandomForestClassifier(),
                           max_samples=0.5, max_features=0.5)

In [104]:
bagging.fit(x_train, y_train)
print(confusion_matrix(y_train, bagging.predict(x_train)))
print(confusion_matrix(y_test, bagging.predict(x_test)))
print('accuracy bagging-bagging: {:0.3f}'.format(accuracy_score(y_test, bagging.predict(x_test))))

[[141   8]
 [  4 245]]
[[ 59   4]
 [  1 107]]
accuracy bagging-bagging: 0.971


D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 

In [ ]:
# Write your code here if base classifier = decision tree!


In [ ]:
# Write your code here if you use RandomForest, compare with above!

from sklearn.ensemble import RandomForestClassifier

## 4. Boosting
Source: https://scikit-learn.org/stable/modules/ensemble.html

### AdaBoost

In [126]:
from sklearn.ensemble import AdaBoostClassifier


clf_ada = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=1),
    n_estimators=200,
learning_rate=1
)

# base_estimator
# Default: Decision Tree (max_depth=1)
# n_estimators
# Default: 50
# learning_rate
# Default: 1.0
# Trade-off between n_estimators and
# learning_rate

clf_ada.fit(x_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=1,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                             

In [127]:
print(confusion_matrix(y_train, clf_ada.predict(x_train)))
print(confusion_matrix(y_test, clf_ada.predict(x_test)))

[[149   0]
 [  0 249]]
[[ 62   1]
 [  2 106]]


In [128]:
print('accuracy Adaboost: {:0.3f}'.format(accuracy_score(y_test, clf_ada.predict(x_test))))

accuracy Adaboost: 0.982


### GradientBoostingClassifier

In [198]:
from sklearn.ensemble import GradientBoostingClassifier

In [201]:
lr_list = [0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in lr_list:
    gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=learning_rate, max_features=2, max_depth=2, random_state=0)
    gb_clf.fit(x_train, y_train)

    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb_clf.score(x_train, y_train)))
    print("Accuracy score (testing): {0:.3f}".format(gb_clf.score(x_test, y_test)))

Learning rate:  0.05
Accuracy score (training): 0.960
Accuracy score (testing): 0.947
Learning rate:  0.075
Accuracy score (training): 0.962
Accuracy score (testing): 0.947
Learning rate:  0.1
Accuracy score (training): 0.962
Accuracy score (testing): 0.947
Learning rate:  0.25
Accuracy score (training): 0.987
Accuracy score (testing): 0.947
Learning rate:  0.5
Accuracy score (training): 0.997
Accuracy score (testing): 0.953
Learning rate:  0.75
Accuracy score (training): 1.000
Accuracy score (testing): 0.971
Learning rate:  1
Accuracy score (training): 1.000
Accuracy score (testing): 0.959


### XGBoost, lightgbm, catboost 

## 5. Stacking  

In [175]:
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from mlxtend.classifier import StackingClassifier
from mlxtend.plotting import plot_decision_regions
import matplotlib.gridspec as gridspec
import itertools

In [182]:
data2 = datasets.load_breast_cancer()

x = data2.data
x = np.asarray(x)

y = data2.target
y = np.asarray(y)

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state = 42)

# Instantiate the 1st-layer classifiers
clf1 = KNeighborsClassifier(n_neighbors=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = DecisionTreeClassifier(max_depth=1)

# Instantiate the 2nd-layer classifier
lr = LogisticRegression()

# Build the Stacking classifier
sclf = StackingClassifier(classifiers=[clf1, clf2, clf3], 
                          meta_classifier=lr,
                          use_probas=False,
                          use_features_in_secondary=False
                         )

sclf.fit(x_train, y_train)
pred = sclf.predict(x_test)

D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [186]:
x.shape

(569, 30)

In [185]:
y.shape

(569,)

In [196]:
for clf, label in zip([clf1, clf2, clf3, sclf], 
                      ['KNN', 
                       'Random Forest', 
                       'Decision Tree',
                       'StackingClassifier']):

    scores = model_selection.cross_val_score(clf, x, y, 
                                              cv=3, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))

Accuracy: 0.91 (+/- 0.02) [KNN]
Accuracy: 0.95 (+/- 0.02) [Random Forest]
Accuracy: 0.88 (+/- 0.01) [Decision Tree]


D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 

Accuracy: 0.92 (+/- 0.03) [StackingClassifier]


In [197]:
print('accuracy Stacking: {:0.3f}'.format(accuracy_score(y_test, sclf.predict(x_test))))

accuracy Stacking: 0.953
